run:
  timeout: 2m
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

issues:
  # show all issues
  max-same-issues: 0
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    # Exclude `lll` issues for long lines with `go:generate`.
    - linters:
        - lll
      source: "^//go:generate "

serverity:
  default-severity: error
  case-sensitive: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - exportloopref
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goerr113
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - ireturn
    - lll
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sloglint
    - staticcheck
    - stylecheck
    - tagalign
    - testifylint
    - testpackage
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

linters-settings:
  dogsled:
    max-blank-identifiers: 2

  dupl:
    threshold: 150

  errcheck:
    check-type-assertions: true
    check-blank: true

  funlen:
    lines: -1 # the number of lines (code + empty lines) is not a right metric and leads to code without empty line or one-liner.
    statements: 60
    ignore-comments: true

  goconst:
    min-len: 2
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - commentedOutCode

  gocyclo:
    min-complexity: 17

  gofmt:
    rewrite-rules:
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'

  gomnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '0666'
      - '0755'
    ignored-functions:
      - strings.SplitN

  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

  lll:
    line-length: 120
    tab-width: 1

  misspell:
    locale: UK

  nestif:
    min-complexity: 7

  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
